// components/meishi/Profile.vue
<template>
  <div>
    <h1>{{ ghdata.name }}</h1>
    <h5>{{ ghdata.login }}</h5>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      ghdata: {}
    }
  },
  mounted () {
    axios.get('https://api.github.com/users/cordx56')
      .then((response) => {
        this.ghdata = response.data
      })
      .catch((error) => {
        window.alert(error)
      })
  }
}
</script>

// components/meishi/profile.tsx
import React, { useState, useEffect } from 'react'
import axios from 'axios'

interface State {
  name: string,
  login: string,
}

const Profile: React.FC = () => {
  const [name, setName] = useState('')
  const [login, setLogin] = useState('')
  useEffect(() => {
    fetchProfile()
  }, [])
  const fetchProfile = () => {
    axios.get('https://api.github.com/users/cordx56')
      .then((response) => {
        setName(response.data.name)
        setLogin(response.data.login)
      })
      .catch((error) => {
        window.alert(error)
      })
  }
  return (
    <div>
      <h1 className="text-4xl font-light">{ name }</h1>
      <h5 className="text-lg text-gray-700">
        @{ login }
      </h5>
    </div>
  )
}

export default Profile
